// Generated by CoffeeScript 1.8.0
(function() {
  var fact, fun, x, y;

  x = 5;

  y = "hello " + x;

  console.log(y);

  fun = function() {
    var b, z;
    x = 3;
    b = 4;
    z = x + b;
    return console.log(z);
  };

  fun('');

  fact = function(number) {
    var f;
    if (number <= 0) {
      return 1;
    }
    f = number * fact(number - 1);
    return f;
  };

  console.log(fact(5));

}).call(this);
